# Generated by Django 3.2.16 on 2024-04-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240403_1726'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='Unique person constraint',
        ),
    ]
